language: node_js
before_install:
  npm install --global gatsby-cli
install: 
  npm install
script: 
  gatsby build
deploy:
  provider: s3
  access_key_id: AKIAJPXLN53JXUTZDQTQ
  secret_access_key:
    secure: ZJCsEyHCIG6nSuLPX6YsxEAJRDEGnUdFiQKZnSeNoUO+DJuVMOEdFieb31dwSA759MeUZleUb63rtBxUsPesf0bgFUCrFJsmAMXF4VYb9mYEHFile8Pd4uic+18DsUvZBXVkMxqgctpeDl4W71GKOI22oZe76txYVq9op/BSkx/39wQyhZfcnHQURPpU/JrU+vjKL3gIDn9OrE5bA2wnPugUgJkcDk6UAFYwFtcN4L/RhC0gCJP0RF0zYW0Ie9YmMu+GFVBVs4kPLIm91nrUpD674jxdXprR3oRVJDoC++pksXnrge0QhJWSG81SOOzAUilGjNT4ZKgI/bMSF3LUqrVwWZx0vKHUV9mHnN/+/u870pUorQs/uEY3gzRhE9FFZ/oqHpVnsjL7SqTzQFZkP97FXRHH79LIkV7X5tf3ndzV9+TmkDPrjqxchzUnRuaGoviBdBKZWu1qtJRLxpZ1Xn5bj4E+fMrRYY2F5ELUOhAugx3ykigNg9SWz4zmsB0IfsYfSJF3yUeP38sYE50Aq91naUVCG6IknFs8upZumUmw9yBkRSxHGbTLCxp4i7o/eRkpLyteiiQ8AjNlsd7j/z9OVjuMuT8Iz9JYd08rZMXrRs9alUcoFmy3L4Qr+gifoo3ktrGnD4iuTy5liaecIHO3dArU39FE1nVjbjNphLY=
  bucket: gatsby-site-test
  local_dir: public
  region: eu-west-3
  acl: 'public_read'
  on:
    repo: MisterAlex95/gatsby-site-test
